services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - kafka_net
    ports:
      - "2181:2181"
    volumes:
      - "~/workspace/volumes/zookeeper:/workspace"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    hostname: kafka
    networks:
      - kafka_net
    ports:
      - "9092:9092"
    volumes:
      - "~/workspace/volumes/kafka:/workspace"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

# volumes:
#   ~/workspace/zookeeper_data:
#     driver: local
#   ~/workspace/kafka_data:
#     driver: local

networks:
  kafka_net: {}